databases:
  - name: rubbergoosedb
    plan: free

services:
  - type: web
    name: rubbergoose-remix
    env: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: npx prisma migrate deploy && npm run start
    healthCheckPath: /healthcheck
    envVars:
      - key: CONTENTFUL_ACCESS_TOKEN
        sync: false
      - key: CONTENTFUL_SPACE_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: rubbergoosedb
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV #required so NODE_ENV is set in build env
        value: production
